version: '4.32.0'

services:
  postgres:
    image: "postgres:15-alpine"
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=core
      - POSTGRES_USER=core
      - POSTGRES_DB=db_core

volumes:
  postgres_data:
